/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kayttoliittyma;

import asiakaskortisto.Asiakas;
import asiakaskortisto.Asiakas.Tila;
import asiakaskortisto.Asiakkaat;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Kati
 */
public class AsiakasValikkoUI extends javax.swing.JFrame {

    static String mitaPainettu;
    Asiakkaat asiakkaat;
    Asiakas vanha;

    /**
     * Creates new form AsiakasValikkoUI
     */
    public AsiakasValikkoUI() throws IOException {
        initComponents();
        // asiakasLista.add("testi1", rootPane);
        asiakkaat = new Asiakkaat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        listaaNappi = new javax.swing.JButton();
        haeNappi = new javax.swing.JButton();
        lisaaNappi = new javax.swing.JButton();
        muutaNappi = new javax.swing.JButton();
        poistaNappi = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        asiakasNimi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        asiakasOsoite = new javax.swing.JTextField();
        asiakasPostinumero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        asiakasYhteyshenkilo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        asiakasPuhelinnumero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        asiakasToimipaikka = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        asiakasNumero = new javax.swing.JTextField();
        okNappi = new javax.swing.JButton();
        viesti = new javax.swing.JLabel();
        poistuNappi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        asiakasLista = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Asiakaskortisto"));

        listaaNappi.setText("Listaa asiakkaat");
        listaaNappi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listaaNappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaaNappiActionPerformed(evt);
            }
        });

        haeNappi.setText("Hae asiakas");
        haeNappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haeNappiActionPerformed(evt);
            }
        });

        lisaaNappi.setText("Lisää asiakas");
        lisaaNappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lisaaNappiActionPerformed(evt);
            }
        });

        muutaNappi.setText("Muuta asiakas");
        muutaNappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muutaNappiActionPerformed(evt);
            }
        });

        poistaNappi.setText("Poista asiakas");
        poistaNappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poistaNappiActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Asiakkaan nimi:");

        jLabel2.setText("Osoite:");

        jLabel3.setText("Postinumero:");

        jLabel4.setText("Yhteyshenkilö:");

        asiakasYhteyshenkilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asiakasYhteyshenkiloActionPerformed(evt);
            }
        });

        jLabel5.setText("Puhelinnumero:");

        asiakasPuhelinnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asiakasPuhelinnumeroActionPerformed(evt);
            }
        });

        jLabel6.setText("Postitoimipaikka:");

        jLabel7.setText("Asiakasnumero:");

        asiakasNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asiakasNumeroActionPerformed(evt);
            }
        });

        okNappi.setText("OK");
        okNappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okNappiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(okNappi)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(asiakasPostinumero, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(asiakasToimipaikka, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                            .addComponent(asiakasNimi)
                            .addComponent(asiakasOsoite))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(asiakasNumero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(asiakasYhteyshenkilo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(asiakasPuhelinnumero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {asiakasNumero, asiakasPuhelinnumero, asiakasYhteyshenkilo});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(asiakasNimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(asiakasNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(asiakasOsoite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asiakasYhteyshenkilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(asiakasPostinumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(asiakasToimipaikka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(asiakasPuhelinnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(okNappi))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {asiakasNumero, asiakasPuhelinnumero, asiakasYhteyshenkilo});

        viesti.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        viesti.setText("Valitse haluamasi toiminto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 103, Short.MAX_VALUE)
                                .addComponent(viesti, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(listaaNappi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(haeNappi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lisaaNappi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(muutaNappi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(poistaNappi, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                        .addGap(68, 68, 68))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(viesti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(listaaNappi)
                    .addComponent(haeNappi)
                    .addComponent(lisaaNappi)
                    .addComponent(muutaNappi)
                    .addComponent(poistaNappi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        poistuNappi.setText("Poistu");
        poistuNappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poistuNappiActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        asiakasLista.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(asiakasLista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(poistuNappi)
                        .addGap(47, 47, 47))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(poistuNappi))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void poistuNappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poistuNappiActionPerformed
        try {
            // TODO add your handling code here:
            asiakkaat.asiakkaatTiedostoon();
        } catch (IOException ex) {
            Logger.getLogger(AsiakasValikkoUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_poistuNappiActionPerformed

    private void asiakasPuhelinnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asiakasPuhelinnumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asiakasPuhelinnumeroActionPerformed

    private void asiakasYhteyshenkiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asiakasYhteyshenkiloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asiakasYhteyshenkiloActionPerformed

    private void asiakasNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asiakasNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asiakasNumeroActionPerformed

    private void listaaNappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaaNappiActionPerformed

        String asiakaslistaus = asiakkaat.listaaAsiakkaat(); // TODO add your handling code here:
        String[] lista = asiakaslistaus.split("\n");

        asiakasLista.setListData(lista);

    }//GEN-LAST:event_listaaNappiActionPerformed

    private void haeNappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haeNappiActionPerformed
        putsaaTiedot();
        viesti.setText("Anna hakuehdoksi asiakkaan nimi tai  asiakasnumero ja paina OK");
        mitaPainettu = "hae";


    }//GEN-LAST:event_haeNappiActionPerformed

    private void okNappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okNappiActionPerformed
        // TODO add your handling code here:
        String haettu;
        String hakutaulu[];
        if (mitaPainettu.equals("hae")) {
            viesti.setText("Haetaan asiakasta");
            haeTiedot();
        }
        if (mitaPainettu.equals("lisaa")) {
            if (tiedotAnnettu()) {
                String postiosoite = asiakasPostinumero.getText();
                postiosoite = postiosoite + " " + asiakasToimipaikka.getText();
                String uusi = asiakkaat.lisaaAsiakas(
                        new Asiakas(asiakasNumero.getText(),
                        asiakasNimi.getText(),
                        asiakasOsoite.getText(),
                        postiosoite,
                        asiakasPuhelinnumero.getText(),
                        asiakasYhteyshenkilo.getText(),
                        "",
                        Tila.NORMAALI));
                String utaulu[] = uusi.split("\n");
                asiakasLista.setListData(utaulu);
                viesti.setText("Asiakastiedot lisätty");
                asiakasNumero.setEditable(true);
                asiakasNumero.setFocusable(rootPaneCheckingEnabled);
                mitaPainettu = "";
            }
        }
        if (mitaPainettu.equals("muuta")) {
            mitaPainettu = "muutaOK";
            viesti.setText("Anna muutettavat tiedot ja paina OK");
            haeTiedot();
        }
        if (mitaPainettu.equals("muutaOK")) {
            if (tiedotAnnettu()) {
                String postiosoite = asiakasPostinumero.getText();
                postiosoite = postiosoite + " " + asiakasToimipaikka.getText();

                asiakkaat.muutaAsiakas(vanha,
                        new Asiakas(asiakasNumero.getText(),
                        asiakasNimi.getText(),
                        asiakasOsoite.getText(),
                        postiosoite,
                        asiakasPuhelinnumero.getText(),
                        asiakasYhteyshenkilo.getText(),
                        "",
                        Tila.NORMAALI));
                Asiakas muutettu = asiakkaat.haeAsiakasOlioAsiakasnumerolla(vanha.getAsiakasNumero());
                asetaAsiakas(muutettu);
                String muuttettuListalle = asiakkaat.haeAsiakasAsiakasnumerolla(vanha.getAsiakasNumero());
                String muutettuTaulu [] = muuttettuListalle.split("\n");
                asiakasLista.setListData(muutettuTaulu);
                
                mitaPainettu.equals("");
                viesti.setText("Asiakastiedot muutettu");
            }
        }

        if (mitaPainettu.equals("poista")) {
            mitaPainettu = "poistaOK";
            viesti.setText("Vahvista poisto painamalla OK");
            haeTiedot();
            
        }
        if (mitaPainettu.equals("poistaOK")) {
            asiakkaat.poistaAsiakas(asiakasNumero.getText());
            putsaaTiedot();
            viesti.setText("Asiakas poistettu");
    }
    }//GEN-LAST:event_okNappiActionPerformed

    private void haeTiedot() {
        String haettu;
        String hakutaulu[];
        if (!asiakasNumero.getText().isEmpty()) {
            haettu = asiakkaat.haeAsiakasAsiakasnumerolla(asiakasNumero.getText());
            hakutaulu = haettu.split("\n");
            asiakasLista.setListData(hakutaulu);
            Asiakas a = asiakkaat.haeAsiakasOlioAsiakasnumerolla(asiakasNumero.getText());
            vanha = a;
            if (a != null) {
                asetaAsiakas(a);
            }

        }
        if (!asiakasNimi.getText().isEmpty()) {
            haettu = asiakkaat.haeAsiakasNimella(asiakasNimi.getText());
            hakutaulu = haettu.split("\n");
            asiakasLista.setListData(hakutaulu);

            Asiakas a = asiakkaat.haeAsiakasOlioNimella(asiakasNimi.getText());
            vanha = a;
            if (a != null) {
                asetaAsiakas(a);
            }
        }
    }

    private void putsaaTiedot() {
        asiakasNimi.setText("");
        asiakasNumero.setEditable(true);
        asiakasNumero.setFocusable(rootPaneCheckingEnabled);
        asiakasNumero.setText("");
        asiakasOsoite.setText("");
        asiakasPostinumero.setText("");
        asiakasToimipaikka.setText("");
        asiakasYhteyshenkilo.setText("");
        asiakasPuhelinnumero.setText("");
        asiakasNimi.grabFocus();

    }

    private void asetaAsiakas(Asiakas a) {
        asiakasNimi.setText(a.getAsiakasNimi());
        asiakasNumero.setEditable(true);
        asiakasNumero.setFocusable(rootPaneCheckingEnabled);
        asiakasNumero.setText(a.getAsiakasNumero());
        asiakasOsoite.setText(a.getKatuOsoite());
        String postiosoite = a.getPostiOsoite();
        String posti[] = postiosoite.split(" ");
        asiakasPostinumero.setText(posti[0]);
        asiakasToimipaikka.setText(posti[1]);
        asiakasYhteyshenkilo.setText(a.getYhteyshenkilo());
        asiakasPuhelinnumero.setText(a.getPuhelinnumero());
    }

    private boolean tiedotAnnettu() {
        if (asiakasNimi.getText().isEmpty()) {
            viesti.setText("Anna asiakkaan nimi");
            asiakasNimi.grabFocus();
            return false;
        }
        if (asiakasOsoite.getText().isEmpty()) {
            viesti.setText("Anna asiakkaan osoite");
            asiakasOsoite.grabFocus();
            return false;
        }
        if (asiakasPostinumero.getText().isEmpty()) {
            viesti.setText("Anna asiakkaan postinumero");
            asiakasPostinumero.grabFocus();
            return false;
        }
        if (asiakasToimipaikka.getText().isEmpty()) {
            viesti.setText("Anna asiakkaan toimipaikka");
            asiakasToimipaikka.grabFocus();
            return false;
        }
        if (asiakasYhteyshenkilo.getText().isEmpty()) {
            viesti.setText("Anna asiakkaan yhteyshenkilo");
            asiakasYhteyshenkilo.grabFocus();
            return false;
        }
        if (asiakasPuhelinnumero.getText().isEmpty()) {
            viesti.setText("Anna asiakkaan puhelinnumero");
            asiakasPuhelinnumero.grabFocus();
            return false;
        }
        return true;
    }

    private void lisaaNappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lisaaNappiActionPerformed
        // TODO add your handling code here:

        putsaaTiedot();
        asiakasNumero.setText(Integer.toString(asiakkaat.getSeuraavaAsiakasnumero()));
        asiakasNumero.setCaretColor(Color.GRAY);
        asiakasNumero.setEditable(false);
        asiakasNumero.setFocusable(false);
        viesti.setText("Anna asiakastiedot kenttiin ja paina OK");
        mitaPainettu = "lisaa";


    }//GEN-LAST:event_lisaaNappiActionPerformed

    private void poistaNappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poistaNappiActionPerformed
        mitaPainettu = "poista";
        putsaaTiedot();
        viesti.setText("Anna poistettavan asiakkaan nimi tai asiakasnumero ja paina OK");


    }//GEN-LAST:event_poistaNappiActionPerformed

    private void muutaNappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muutaNappiActionPerformed
        // TODO add your handling code here:
        mitaPainettu = "muuta";
        putsaaTiedot();
        viesti.setText("Anna muutettavan asiakkaan nimi tai asiakasnumero ja paina OK");

    }//GEN-LAST:event_muutaNappiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsiakasValikkoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsiakasValikkoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsiakasValikkoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsiakasValikkoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    new AsiakasValikkoUI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(AsiakasValikkoUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList asiakasLista;
    private javax.swing.JTextField asiakasNimi;
    private javax.swing.JTextField asiakasNumero;
    private javax.swing.JTextField asiakasOsoite;
    private javax.swing.JTextField asiakasPostinumero;
    private javax.swing.JTextField asiakasPuhelinnumero;
    private javax.swing.JTextField asiakasToimipaikka;
    private javax.swing.JTextField asiakasYhteyshenkilo;
    private javax.swing.JButton haeNappi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lisaaNappi;
    private javax.swing.JButton listaaNappi;
    private javax.swing.JButton muutaNappi;
    private javax.swing.JButton okNappi;
    private javax.swing.JButton poistaNappi;
    private javax.swing.JButton poistuNappi;
    private javax.swing.JLabel viesti;
    // End of variables declaration//GEN-END:variables
}
