/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kayttoliittyma;

import asiakaskortisto.Kayttaja;
import asiakaskortisto.Kayttaja.Rooli;
import asiakaskortisto.Kirjaudu;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Kati
 */
public class KirjautumisUI extends javax.swing.JFrame {

    static int kirjautumisLaskuri;

    /**
     * Creates new form KirjautumisUI
     */
    public KirjautumisUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kayttajatunnusLabel = new javax.swing.JLabel();
        salasanaLabel = new javax.swing.JLabel();
        kayttajatunnus = new javax.swing.JTextField();
        Kirjaudu = new javax.swing.JButton();
        salasana = new javax.swing.JTextField();
        viesti = new javax.swing.JLabel();
        Poistu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Asiakaskortisto"));

        kayttajatunnusLabel.setText("Käyttäjätunnus");

        salasanaLabel.setText("Salasana");

        Kirjaudu.setText("Kirjaudu");
        Kirjaudu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KirjauduActionPerformed(evt);
            }
        });

        viesti.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        viesti.setText("Anna käyttäjätunnus ja salasana");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kayttajatunnusLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salasanaLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salasana, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(kayttajatunnus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Kirjaudu))
                    .addComponent(viesti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(86, 86, 86))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {kayttajatunnus, salasana});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viesti, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kayttajatunnus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kayttajatunnusLabel))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salasanaLabel)
                    .addComponent(salasana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(Kirjaudu)
                .addGap(29, 29, 29))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {kayttajatunnus, salasana});

        Poistu.setText("Poistu");
        Poistu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PoistuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Poistu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Poistu)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KirjauduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KirjauduActionPerformed

        Rooli kirjautujanrooli = null;
        String kayttajaTunnus = kayttajatunnus.getText();
        String salaSana = salasana.getText();
        //char[] salaSana = salasana.getPassword();
        
        kirjautumisLaskuri++;
        if (kirjautumisLaskuri > 2) {
            System.out.println("Kirjautuminen ei onnistunut");
            System.exit(0);
        }
        if (!kayttajaTunnus.isEmpty() && !salaSana.isEmpty()) {
            try {

                Kirjaudu kirjaudu = new Kirjaudu();
                kirjautujanrooli = kirjaudu.tarkistaKirjautuminen(new Kayttaja(kayttajaTunnus, salaSana));

            } catch (IOException ex) {
                Logger.getLogger(KirjautumisUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
            
 
        viesti.setText("Yritä uudelleen");
        if (kirjautujanrooli == null && kirjautumisLaskuri > 2) {
            System.out.println("Kirjautuminen ei onnistunut");
            System.exit(0);
        }
        
        if (kirjautujanrooli == Rooli.YLLAPITO) {
            System.out.println("ylläpito");
        }
        if (kirjautujanrooli == Rooli.ESIMIES) {
            System.out.println("esimies");
        }
        if (kirjautujanrooli == Rooli.TYONTEKIJA) {
            System.out.println("työntekijä");
        }
    }//GEN-LAST:event_KirjauduActionPerformed

    private void PoistuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PoistuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_PoistuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KirjautumisUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KirjautumisUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KirjautumisUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KirjautumisUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new KirjautumisUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Kirjaudu;
    private javax.swing.JButton Poistu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kayttajatunnus;
    private javax.swing.JLabel kayttajatunnusLabel;
    private javax.swing.JTextField salasana;
    private javax.swing.JLabel salasanaLabel;
    private javax.swing.JLabel viesti;
    // End of variables declaration//GEN-END:variables
}
